name: fizz-buzz-typescript
services:
  appserver:
    type: node:12
    ssl: false
    command: tail -f /dev/null
    build:
      - npm install
      - npm run-script build
tooling:
  fizzbuzz:
    service: appserver
    cmd: npm run-script fizzbuzz
  tsc:
    service: appserver
    cmd: npx tsc
  npm:
    service: appserver
  npx:
    service: appserver
  tslint:
    service: appserver
    cmd: npx tslint --project /app
