name: fizz-buzz-typescript
services:
  appserver:
    type: node:12
    ssl: false
    command: tail -f /dev/null
    globals: []
tooling:
  fizzbuzz:
    service: appserver
    cmd: npm run-script fizzbuzz
  tsc:
    service: appserver
    cmd: tsc
  npm:
    service: appserver
  tslint:
    service: appserver
    cmd: tslint --project /app
