name: fizz-buzz-typescript
services:
  main:
    type: node:12
    ssl: false
    command: tail -f /dev/null
    build:
      - npm install
      - npm run-script build
tooling:
  fizzbuzz:
    service: main
    cmd: npm run-script fizzbuzz
  tsc:
    service: main
    cmd: npx tsc
  npm:
    service: main
  npx:
    service: main
  lint:
    service: main
    cmd: npx tslint --project /app
  test:
    service: main
    cmd: npm run-script test
