name: validation
on:
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Prepare
        run: npm ci
      - name: Lint
        run: npx tslint --project $PWD
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Prepare
        run: npm ci
      - name: Transpile
        run: npx tsc
      - name: Test
        run: npm test
